# Generated by Django 5.2.13 on 2026-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACMEProvisioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='forgedca-acme', help_text='Provisioner name — appears in the ACME directory URL (https://<host>:9000/acme/<name>/directory). Changing this breaks existing bootstrapped clients until they re-bootstrap.', max_length=63)),
                ('enabled', models.BooleanField(default=True, help_text='If disabled, step-ca will reject every ACME request. Useful for maintenance windows or when the admin wants to lock down issuance temporarily.')),
                ('default_leaf_lifetime_hours', models.PositiveIntegerField(default=1176, help_text="Lifetime issued when the client doesn't request a specific duration. 49 days matches the 2029 public-web ceiling.")),
                ('min_leaf_lifetime_hours', models.PositiveIntegerField(default=1)),
                ('max_leaf_lifetime_hours', models.PositiveIntegerField(default=8760)),
                ('challenge_http01', models.BooleanField(default=True, help_text='HTTP-01: CA fetches /.well-known/acme-challenge/<token> on port 80. Baseline — keep enabled.')),
                ('challenge_tls_alpn01', models.BooleanField(default=False, help_text='TLS-ALPN-01: CA opens a TLS connection with the acme-tls/1 protocol. Useful when the client owns port 443 but not port 80.')),
                ('challenge_dns01', models.BooleanField(default=False, help_text='DNS-01: CA checks a TXT record. Requires a DNS-provider plugin (AWS Route 53, Cloudflare, RFC 2136, …). The plugin UI ships in a later slice; leave off for now.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ACME provisioner',
            },
        ),
    ]
