# Generated by Django 5.2.13 on 2026-04-19 16:35
#
# Data-preserving conversion from per-provisioner lifetime fields to a
# CertTemplate FK. Order:
#   1. Add the template FK (nullable for the data-migration step).
#   2. Data-migrate: read the old lifetime fields, find or create a matching
#      CertTemplate, bind each provisioner to it.
#   3. Drop the three old fields now that the FK is populated.
#
# An admin who had customised their ACME lifetimes won't silently lose them —
# the old values end up on a custom CertTemplate called "Legacy ACME lifetime"
# and the provisioner stays bound to it.

import django.db.models.deletion
from django.db import migrations, models


def migrate_lifetimes_to_template(apps, schema_editor):
    ACMEProvisioner = apps.get_model("acme", "ACMEProvisioner")
    CertTemplate    = apps.get_model("templates_app", "CertTemplate")

    # Ensure the seeded default exists (the live load_default() isn't usable
    # here — historical models don't have classmethods).
    default, _ = CertTemplate.objects.get_or_create(
        slug="web-server",
        defaults={
            "name": "Web Server (Server + Client Auth)",
            "description": (
                "Out-of-the-box default for ACME-enrolled web servers. "
                "Matches how Let's Encrypt and most public CAs issue leaves "
                "today — serverAuth + clientAuth EKUs, 49-day lifetime."
            ),
            "is_system": True,
            "default_lifetime_days": 49,
            "min_lifetime_days": 1,
            "max_lifetime_days": 825,
        },
    )

    for p in ACMEProvisioner.objects.all():
        # Old fields stored HOURS. Convert to days for the template shape.
        def_days = (p.default_leaf_lifetime_hours or 49 * 24) // 24
        min_days = max(1, (p.min_leaf_lifetime_hours  or 1)          // 24)
        max_days = (p.max_leaf_lifetime_hours  or 825 * 24) // 24

        matches_default = (
            def_days == default.default_lifetime_days
            and min_days == default.min_lifetime_days
            and max_days == default.max_lifetime_days
        )
        if matches_default:
            p.template = default
        else:
            legacy, _ = CertTemplate.objects.get_or_create(
                slug="legacy-acme-lifetime",
                defaults={
                    "name": "Legacy ACME lifetime (from slice 2B)",
                    "description": (
                        "Carried over from the per-provisioner lifetime fields "
                        "before slice 3 introduced templates. Rename or replace "
                        "this — it captures whatever lifetime you'd set on the "
                        "ACME page before the migration."
                    ),
                    "is_system": False,
                    "default_lifetime_days": def_days,
                    "min_lifetime_days":     min_days,
                    "max_lifetime_days":     max_days,
                },
            )
            p.template = legacy
        p.save(update_fields=["template"])


def reverse_noop(apps, schema_editor):
    # Backwards path: the old fields get re-added (via schema reversal) but
    # we can't safely reconstruct them from the FK without fresh data, so
    # leave the lifetime fields at whatever Django's AddField default sets
    # them to. Pure rollback is a dev-only operation anyway.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmeprovisioner',
            name='template',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='acme_provisioners',
                to='templates_app.certtemplate',
                help_text=(
                    'Cert template whose lifetime + policy applies to leaves '
                    'issued via this provisioner. Defaults to the seeded '
                    'Web Server template if unset.'
                ),
            ),
        ),
        migrations.RunPython(migrate_lifetimes_to_template, reverse_noop),
        migrations.RemoveField(
            model_name='acmeprovisioner',
            name='default_leaf_lifetime_hours',
        ),
        migrations.RemoveField(
            model_name='acmeprovisioner',
            name='max_leaf_lifetime_hours',
        ),
        migrations.RemoveField(
            model_name='acmeprovisioner',
            name='min_leaf_lifetime_hours',
        ),
    ]
