# Generated by Django 5.2.13 on 2026-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Short internal identifier, used in URLs and API calls.', max_length=63, unique=True)),
                ('name', models.CharField(help_text='Human-facing name shown on the provisioner picker.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Short one-liner telling admins when to pick this template.')),
                ('is_system', models.BooleanField(default=False, help_text="System templates (the seeded default) can't be deleted — they guarantee every provisioner always has a binding.")),
                ('default_lifetime_days', models.PositiveIntegerField(default=49, help_text="Issued when the client doesn't request a specific duration. 49 matches CA/B's 2029 public-web ceiling with a small margin for renewal crons.")),
                ('min_lifetime_days', models.PositiveIntegerField(default=1, help_text="Floor the CA will accept. Clients asking for less get rejected; most clients ask for 'not-after' so this is effectively a safety stop.")),
                ('max_lifetime_days', models.PositiveIntegerField(default=825, help_text='Ceiling the CA will issue. Clients asking for more get silently capped at this value.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'certificate template',
                'ordering': ['-is_system', 'name'],
            },
        ),
    ]
