# Generated by Django 5.2.13 on 2026-08-02 07:47
#
# Help-text only. The Slice 3.7 enforcement commit rewrote
# extended_key_usages.help_text ("declared policy" -> "enforced at
# issuance") without a matching migration, leaving makemigrations
# permanently dirty. No schema or data change.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0002_eku_ku_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certtemplate",
            name="extended_key_usages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="What this certificate is allowed to be used for. Stored as OpenSSL-style short names (e.g. 'serverAuth', 'clientAuth'). Enforced at issuance — step-ca writes exactly these EKU bits on every cert it issues against any provisioner bound to this template, regardless of what the CSR requests.",
            ),
        ),
    ]
