# Generated by Django 5.2.13 on 2026-04-19 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Certificate serial number (uppercase hex)', max_length=64, unique=True)),
                ('common_name', models.CharField(blank=True, help_text='Certificate Common Name', max_length=255)),
                ('sans', models.TextField(blank=True, help_text='Subject Alternative Names (one per line)')),
                ('template_name', models.CharField(blank=True, help_text='Snapshot of template name at time of issuance', max_length=120)),
                ('is_passthrough', models.BooleanField(default=False, help_text='True if passthrough signing was used (bypassed template policy)')),
                ('extended_key_usages', models.JSONField(default=list, help_text='EKUs that were actually issued')),
                ('key_usages', models.JSONField(default=list, help_text='KUs that were actually issued')),
                ('not_before', models.DateTimeField(help_text='Certificate validity start')),
                ('not_after', models.DateTimeField(help_text='Certificate validity end')),
                ('signer_tier', models.CharField(blank=True, choices=[('issuing', 'Issuing CA'), ('intermediate', 'Intermediate CA'), ('root', 'Root CA')], help_text='Which tier signed this certificate', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual CSR signing'), ('acme', 'ACME auto-enrollment')], default='manual', help_text='Source of this certificate issuance', max_length=16)),
                ('certificate_pem', models.TextField(help_text='Issued certificate in PEM format')),
                ('csr_pem', models.TextField(blank=True, help_text='Original CSR in PEM format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this certificate was issued')),
                ('csr', models.ForeignKey(blank=True, help_text='Original CSR that was signed', on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.certtemplate')),
            ],
            options={
                'verbose_name': 'issued certificate',
                'verbose_name_plural': 'issued certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]