# Generated by Django 4.2.16 on 2026-08-22 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_app', '0003_eku_help_text'),
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcertificate',
            name='csr',
            field=models.ForeignKey(blank=True, help_text='Original CSR that was signed (reserved for future ACME integration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for issuance (null if passthrough or template deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.certtemplate'),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='template_name',
            field=models.CharField(blank=True, help_text='Snapshot of template name at time of issuance (survives template rename/delete)', max_length=120),
        ),
    ]
